from Battleship import *

game = Play()
game.cpu_setup()
game.player_setup()
print("Setting up the game")
print("YOUR GRID")
game.player_1.print_grid(True)
print("CPU GRID")
game.player_1.print_grid()
""" player_1 = Battleship()
player_1.add_boat("Carrier","A0","Horizontal")
player_1.add_boat("Battleship","B0","Vertical")
player_1.add_boat("Cruiser","D4","Horizontal")
player_1.add_boat("Submarine","E5","Horizontal")
player_1.add_boat("Destroyer","E7","Horizontal")
print("             YOUR GRID:")
player_1.print_grid(True) """
"""
cpu = Battleship()
cpu.add_boat("Carrier","A3","Vertical")
cpu.add_boat("Battleship","J4","Vertical")
cpu.add_boat("Cruiser","D4","Horizontal")
cpu.add_boat("Submarine","E5","Horizontal")
cpu.add_boat("Destroyer","E7","Horizontal")
print("             CPU GRID:")
cpu.print_grid()

player_1.bomb("A3",cpu)
player_1.bomb("A4",cpu)
player_1.bomb("B3",cpu)
print(print_grid(cpu.grid, False))
player_1.bomb("B3",cpu)
print("             CPU GRID:")
print(print_grid(cpu.grid, False))
print(player_1.boats)
player_1.bomb("A1",cpu)
player_1.bomb("A2",cpu)
player_1.bomb("A5",cpu)
player_1.bomb("A6",cpu)
player_1.bomb("A7",cpu)
print(print_grid(cpu.grid, False))
print(player_1.sunk)
print(cpu.boats) """
    